### PR TITLE
move from svn to git for static.mozilla.com content

### PR DESCRIPTION
**Pull request by danielhartnell**
I pulled the svn content for the site from [svn.mozilla.org](https://svn.mozilla.org/projects/static.mozilla.com/trunk) and moved it to GitHub:

https://github.com/mozilla-it/static.mozilla.com.git

I believe that this should work correctly. I am actually curious if the top level `trunk` folder is required in the new git repository. If I were to `svn co https://svn.mozilla.org/projects/static.mozilla.com/trunk`, I would end up with that. I'm not sure if that happens when Jenkins checks out the svn repository.

I'm having trouble following the sync logic in Haul to be 100% sure that the same content will end up in the Apache doc root.

### CODE REVIEW

**Comment by floatingatoll** [comment]
It would be extremely nice if we could avoid having a vestigal trunk
directory in the git repository, no matter what it takes to make that
happen, given that otherwise we'll make it vastly more difficult for new
people to understand when they encounter it: "Wait, git trunk? Is this an
SVN repo? (panic ensues)"

**Comment by gozer** [comment]
You are also losing all history in this copy. Would be better to use git-svn to import all history and this way, you also get branches along (i.e. trunk)

**Comment by danielhartnell** [comment]
I have already had that discussion and we agreed it wasn't necessary to deal with copying over the history right now. That said, it's not going to hurt anything so I can go ahead and look into it. I don't think that needs to block this PR though.

**Comment by limed** [comment]
I had done this recently I believe sort of a short of how i did this was with git-svn

```
git svn clone svn+ssh://svn.mozilla.org/path/to/your/project <foldername>
cd <foldername>
git remote add git-repo <location of git repo here>
git push git-repo master
```

Somewhere along those lines

**Pull request merged**
